name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install Node.js and NPM (Backend)
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: 'npm'
                  cache-dependency-path: ./backend/package-lock.json

            - name: Install project dependencies (Backend)
              run: npm install
              working-directory: backend

            - name: Build TypeScript to JavaScript (Backend)
              run: npm run build
              working-directory: backend

            - name: Check styles with ESLint (Backend)
              run: npm run lint
              working-directory: backend

            - name: Install Node.js and NPM (Frontend)
              uses: actions/setup-node@v2
              with:
                  node-version: 16.x
                  cache: 'npm'
                  cache-dependency-path: ./frontend/package-lock.json

            - name: Install project dependencies (Frontend)
              run: npm install
              working-directory: frontend

            - name: Build TypeScript to JavaScript (Frontend)
              run: npm run build
              working-directory: frontend
